### ISSUE TITLE
No hyphens allowed (@template TKey of array-key) after update to v1.6.0

### ISSUE THREAD

**Issue by rumours86** [doctrine/collections#182]
Don't use hyphens 
 * @template TKey of array-key

```
composer req vimeo/psalm

php vendor/bin/psalm --show-info=false

Scanning files...

Fatal error: Uncaught Psalm\Exception\TypeParseTreeException: no hyphens allowed in /var/www/stf/vendor/vimeo/psalm/src/Psalm/Type/Atomic.php:129
Stack trace:
#0 /var/www/stf/vendor/vimeo/psalm/src/Psalm/Type.php(117): Psalm\Type\Atomic::create('Doctrine\\Common...', false, Array)
#1 /var/www/stf/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(661): Psalm\Type::parseTokens(Array)
#2 /var/www/stf/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(200): Psalm\Visitor\DependencyFinderVisitor->registerClassLike(Object(PhpParser\Node\Stmt\Interface_))
#3 /var/www/stf/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Visitor\DependencyFinderVisitor->enterNode(Object(PhpParser\Node\Stmt\Interface_))
#4 /var/www/stf/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#5 /var/www/stf/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#6 /va in /var/www/stf/vendor/vimeo/psalm/src/Psalm/Type/Atomic.php on line 129
```

**Comment by Ocramius** [comment]
This on latest releases of psalm?

**Comment by rumours86** [comment]
yes
 php vendor/bin/psalm --version
Psalm 2.0.17@ead7d62d489d58edb4fa03b21e4f0bc87a476211

**Comment by Ocramius** [comment]
https://github.com/doctrine/collections/blob/v1.6.0/composer.json

**Comment by rumours86** [comment]
Thank you
